/* =================================================================
   GamifyDeals.com – games data (200+ Steam titles)
   ================================================================= */

const GAMES_DATA = [

  /* ── ACTION ─────────────────────────────────────────── */
  { id:271590,  name:"Grand Theft Auto V",               genre:"Action",   sub:"Open World",    price:149, orig:1799, badge:"hot",        emoji:"🏙️" },
  { id:1174180, name:"Red Dead Redemption 2",             genre:"Action",   sub:"Adventure",     price:179, orig:2999, badge:"bestseller",  emoji:"🤠" },
  { id:208650,  name:"Batman: Arkham Knight",             genre:"Action",   sub:"Superhero",     price:99,  orig:999,  badge:"",            emoji:"🦇" },
  { id:200260,  name:"Batman: Arkham City",               genre:"Action",   sub:"Superhero",     price:79,  orig:699,  badge:"",            emoji:"🦇" },
  { id:35140,   name:"Batman: Arkham Asylum",             genre:"Action",   sub:"Superhero",     price:69,  orig:499,  badge:"",            emoji:"🦇" },
  { id:1817070, name:"Spider-Man: Miles Morales",         genre:"Action",   sub:"Superhero",     price:199, orig:3499, badge:"hot",         emoji:"🕷️" },
  { id:1593500, name:"God of War",                        genre:"Action",   sub:"Mythology",     price:189, orig:2999, badge:"bestseller",  emoji:"⚔️" },
  { id:1475810, name:"Ghostwire: Tokyo",                  genre:"Action",   sub:"Supernatural",  price:99,  orig:2499, badge:"",            emoji:"👁️" },
  { id:1252330, name:"Deathloop",                         genre:"Action",   sub:"FPS",           price:89,  orig:1999, badge:"",            emoji:"🔁" },
  { id:2215430, name:"Ghost of Tsushima: Director's Cut", genre:"Action",   sub:"Samurai",       price:219, orig:3999, badge:"new",         emoji:"⛩️" },
  { id:1259420, name:"Watch Dogs Legion",                 genre:"Action",   sub:"Stealth",       price:99,  orig:1799, badge:"",            emoji:"🤖" },
  { id:447040,  name:"Watch Dogs 2",                      genre:"Action",   sub:"Open World",    price:79,  orig:999,  badge:"",            emoji:"🤖" },
  { id:241930,  name:"Middle-Earth: Shadow of Mordor",    genre:"Action",   sub:"Fantasy",       price:79,  orig:699,  badge:"",            emoji:"💍" },
  { id:356190,  name:"Middle-Earth: Shadow of War",       genre:"Action",   sub:"Fantasy",       price:89,  orig:999,  badge:"",            emoji:"⚔️" },
  { id:1030840, name:"Mafia: Definitive Edition",         genre:"Action",   sub:"Crime",         price:99,  orig:1499, badge:"",            emoji:"🎩" },
  { id:360430,  name:"Mafia III: Definitive Edition",     genre:"Action",   sub:"Crime",         price:89,  orig:999,  badge:"",            emoji:"🎩" },
  { id:638970,  name:"Yakuza 0",                          genre:"Action",   sub:"Crime",         price:79,  orig:699,  badge:"bestseller",  emoji:"🥊" },
  { id:834530,  name:"Yakuza Kiwami",                     genre:"Action",   sub:"Crime",         price:69,  orig:599,  badge:"",            emoji:"🥊" },
  { id:927380,  name:"Yakuza Kiwami 2",                   genre:"Action",   sub:"Crime",         price:79,  orig:699,  badge:"",            emoji:"🥊" },
  { id:1235140, name:"Yakuza: Like a Dragon",             genre:"Action",   sub:"RPG",           price:99,  orig:1499, badge:"",            emoji:"🥊" },
  { id:2058180, name:"Judgment",                          genre:"Action",   sub:"Crime",         price:89,  orig:1499, badge:"",            emoji:"⚖️" },
  { id:1283100, name:"Lost Judgment",                     genre:"Action",   sub:"Crime",         price:99,  orig:1999, badge:"",            emoji:"⚖️" },
  { id:775500,  name:"Scarlet Nexus",                     genre:"Action",   sub:"Anime",         price:89,  orig:1499, badge:"",            emoji:"🧠" },
  { id:1172380, name:"Star Wars Jedi: Fallen Order",      genre:"Action",   sub:"Sci-Fi",        price:99,  orig:1499, badge:"bestseller",  emoji:"⚔️" },
  { id:1756130, name:"Star Wars Jedi: Survivor",          genre:"Action",   sub:"Sci-Fi",        price:149, orig:2999, badge:"new",         emoji:"⚔️" },
  { id:1088850, name:"Guardians of the Galaxy",           genre:"Action",   sub:"Superhero",     price:99,  orig:1499, badge:"",            emoji:"🦝" },
  { id:239140,  name:"Dying Light",                       genre:"Action",   sub:"Parkour",       price:79,  orig:999,  badge:"",            emoji:"🌃" },
  { id:1583230, name:"High on Life",                      genre:"Action",   sub:"Comedy",        price:79,  orig:1499, badge:"",            emoji:"🔫" },
  { id:987720,  name:"Marvel's Avengers",                 genre:"Action",   sub:"Superhero",     price:69,  orig:999,  badge:"",            emoji:"🛡️" },
  { id:268910,  name:"Cuphead",                           genre:"Action",   sub:"Run & Gun",     price:79,  orig:699,  badge:"bestseller",  emoji:"☕" },
  { id:1229490, name:"ULTRAKILL",                         genre:"Action",   sub:"FPS",           price:69,  orig:799,  badge:"new",         emoji:"🔫" },
  { id:1326470, name:"Sons of The Forest",                genre:"Action",   sub:"Survival",      price:89,  orig:999,  badge:"new",         emoji:"🌲" },
  { id:250760,  name:"Shovel Knight: Treasure Trove",     genre:"Action",   sub:"Platformer",    price:49,  orig:399,  badge:"",            emoji:"⚔️" },
  { id:1145360, name:"Hades",                             genre:"Action",   sub:"Roguelite",     price:69,  orig:699,  badge:"",            emoji:"💀" },
  { id:367520,  name:"Hollow Knight",                     genre:"Action",   sub:"Metroidvania",  price:49,  orig:399,  badge:"",            emoji:"🐛" },
  { id:504230,  name:"Celeste",                           genre:"Action",   sub:"Platformer",    price:49,  orig:399,  badge:"",            emoji:"⛰️" },

  /* ── RPG ─────────────────────────────────────────────── */
  { id:1091500, name:"Cyberpunk 2077",                    genre:"RPG",      sub:"Open World",    price:199, orig:3999, badge:"hot",         emoji:"🌆" },
  { id:292030,  name:"The Witcher 3: Wild Hunt",          genre:"RPG",      sub:"Fantasy",       price:149, orig:2499, badge:"bestseller",  emoji:"🐺" },
  { id:1245620, name:"Elden Ring",                        genre:"RPG",      sub:"Souls-like",    price:249, orig:3999, badge:"new",         emoji:"💍" },
  { id:990080,  name:"Hogwarts Legacy",                   genre:"RPG",      sub:"Magic",         price:229, orig:3999, badge:"hot",         emoji:"⚡" },
  { id:374320,  name:"Dark Souls 3",                      genre:"RPG",      sub:"Souls-like",    price:129, orig:1799, badge:"",            emoji:"🔥" },
  { id:814380,  name:"Sekiro: Shadows Die Twice",         genre:"RPG",      sub:"Souls-like",    price:169, orig:2499, badge:"",            emoji:"🎋" },
  { id:582010,  name:"Monster Hunter: World",             genre:"RPG",      sub:"Co-op",         price:119, orig:1499, badge:"",            emoji:"🐉" },
  { id:1446780, name:"Monster Hunter Rise",               genre:"RPG",      sub:"Co-op",         price:129, orig:1999, badge:"",            emoji:"🐉" },
  { id:377160,  name:"Fallout 4",                         genre:"RPG",      sub:"Post-Apocalyptic",price:89,orig:999, badge:"",            emoji:"☢️" },
  { id:1151640, name:"Horizon Zero Dawn",                 genre:"RPG",      sub:"Sci-Fi",        price:129, orig:1699, badge:"",            emoji:"🏹" },
  { id:1086940, name:"Baldur's Gate 3",                   genre:"RPG",      sub:"Turn-based",    price:249, orig:3999, badge:"bestseller",  emoji:"🎲" },
  { id:435150,  name:"Divinity: Original Sin 2",          genre:"RPG",      sub:"Turn-based",    price:119, orig:1499, badge:"bestseller",  emoji:"🎲" },
  { id:367500,  name:"Dragon's Dogma: Dark Arisen",       genre:"RPG",      sub:"Fantasy",       price:79,  orig:699,  badge:"",            emoji:"🐉" },
  { id:2054970, name:"Dragon's Dogma 2",                  genre:"RPG",      sub:"Fantasy",       price:199, orig:3999, badge:"new",         emoji:"🐉" },
  { id:524220,  name:"NieR: Automata",                    genre:"RPG",      sub:"Sci-Fi",        price:99,  orig:1499, badge:"bestseller",  emoji:"🤖" },
  { id:1113560, name:"NieR Replicant",                    genre:"RPG",      sub:"Dark Fantasy",  price:89,  orig:1499, badge:"",            emoji:"📖" },
  { id:1687950, name:"Persona 5 Royal",                   genre:"RPG",      sub:"JRPG",          price:149, orig:2499, badge:"hot",         emoji:"🎭" },
  { id:1113000, name:"Persona 4 Golden",                  genre:"RPG",      sub:"JRPG",          price:79,  orig:799,  badge:"",            emoji:"🔮" },
  { id:921570,  name:"Octopath Traveler",                 genre:"RPG",      sub:"JRPG",          price:89,  orig:1499, badge:"",            emoji:"🗡️" },
  { id:1765190, name:"Octopath Traveler 2",               genre:"RPG",      sub:"JRPG",          price:109, orig:1999, badge:"new",         emoji:"🗡️" },
  { id:1716740, name:"Starfield",                         genre:"RPG",      sub:"Sci-Fi",        price:199, orig:3499, badge:"new",         emoji:"🚀" },
  { id:489830,  name:"Skyrim Special Edition",            genre:"RPG",      sub:"Fantasy",       price:99,  orig:999,  badge:"bestseller",  emoji:"🗡️" },
  { id:637650,  name:"Final Fantasy XV",                  genre:"RPG",      sub:"JRPG",          price:89,  orig:1499, badge:"",            emoji:"⚔️" },
  { id:1462040, name:"Final Fantasy VII Remake",          genre:"RPG",      sub:"JRPG",          price:149, orig:2999, badge:"hot",         emoji:"⚔️" },
  { id:429660,  name:"Tales of Berseria",                 genre:"RPG",      sub:"JRPG",          price:69,  orig:999,  badge:"",            emoji:"⚔️" },
  { id:1047900, name:"Tales of Arise",                    genre:"RPG",      sub:"JRPG",          price:99,  orig:1999, badge:"",            emoji:"⚔️" },
  { id:678960,  name:"Code Vein",                         genre:"RPG",      sub:"Souls-like",    price:89,  orig:1499, badge:"",            emoji:"🧛" },
  { id:1328670, name:"Mass Effect Legendary Edition",     genre:"RPG",      sub:"Sci-Fi",        price:149, orig:2499, badge:"bestseller",  emoji:"🚀" },
  { id:851850,  name:"Dragon Ball Z: Kakarot",            genre:"RPG",      sub:"Anime",         price:99,  orig:1999, badge:"",            emoji:"🐉" },
  { id:1058510, name:"One Piece Odyssey",                 genre:"RPG",      sub:"Anime",         price:99,  orig:1999, badge:"",            emoji:"🏴‍☠️" },
  { id:640820,  name:"Pathfinder: Kingmaker",             genre:"RPG",      sub:"isometric",     price:79,  orig:999,  badge:"",            emoji:"👑" },
  { id:2679460, name:"Metaphor: ReFantazio",              genre:"RPG",      sub:"JRPG",          price:199, orig:3999, badge:"new",         emoji:"🧙" },
  { id:1184370, name:"Pathfinder: Wrath of the Righteous",genre:"RPG",     sub:"isometric",     price:89,  orig:1499, badge:"",            emoji:"👑" },

  /* ── SHOOTER ─────────────────────────────────────────── */
  { id:782330,  name:"DOOM Eternal",                      genre:"Shooter",  sub:"FPS",           price:109, orig:1499, badge:"hot",         emoji:"🔫" },
  { id:1449560, name:"Metro Exodus Enhanced Edition",     genre:"Shooter",  sub:"Survival",      price:99,  orig:1499, badge:"",            emoji:"🚂" },
  { id:933440,  name:"Far Cry 6",                         genre:"Shooter",  sub:"Open World",    price:119, orig:2999, badge:"",            emoji:"🌴" },
  { id:397540,  name:"Borderlands 3",                     genre:"Shooter",  sub:"Looter",        price:99,  orig:1999, badge:"",            emoji:"🤠" },
  { id:1659040, name:"Hitman World of Assassination",     genre:"Shooter",  sub:"Stealth",       price:109, orig:1999, badge:"",            emoji:"🎯" },
  { id:1517290, name:"Battlefield 2042",                  genre:"Shooter",  sub:"Multiplayer",   price:89,  orig:2499, badge:"",            emoji:"🪖" },
  { id:1263950, name:"Battlefield V",                     genre:"Shooter",  sub:"Multiplayer",   price:69,  orig:999,  badge:"",            emoji:"🪖" },
  { id:1238820, name:"Battlefield 1",                     genre:"Shooter",  sub:"Multiplayer",   price:69,  orig:999,  badge:"",            emoji:"🪖" },
  { id:359550,  name:"Rainbow Six Siege",                 genre:"Shooter",  sub:"Tactical",      price:79,  orig:999,  badge:"bestseller",  emoji:"🎯" },
  { id:550,     name:"Left 4 Dead 2",                     genre:"Shooter",  sub:"Co-op",         price:49,  orig:399,  badge:"bestseller",  emoji:"🧟" },
  { id:218620,  name:"PAYDAY 2",                          genre:"Shooter",  sub:"Heist",         price:49,  orig:399,  badge:"",            emoji:"💰" },
  { id:1604030, name:"PAYDAY 3",                          genre:"Shooter",  sub:"Heist",         price:89,  orig:1999, badge:"",            emoji:"💰" },
  { id:548430,  name:"Deep Rock Galactic",                genre:"Shooter",  sub:"Co-op",         price:79,  orig:999,  badge:"bestseller",  emoji:"⛏️" },
  { id:553850,  name:"Helldivers 2",                      genre:"Shooter",  sub:"Co-op",         price:129, orig:2499, badge:"hot",         emoji:"🪖" },
  { id:581320,  name:"Insurgency: Sandstorm",             genre:"Shooter",  sub:"Tactical",      price:79,  orig:799,  badge:"",            emoji:"🎖️" },
  { id:594650,  name:"Hunt: Showdown",                    genre:"Shooter",  sub:"Battle Royale", price:89,  orig:1499, badge:"",            emoji:"🏹" },
  { id:1144400, name:"Ready or Not",                      genre:"Shooter",  sub:"Tactical",      price:89,  orig:1499, badge:"new",         emoji:"🚔" },
  { id:632360,  name:"Risk of Rain 2",                    genre:"Shooter",  sub:"Roguelite",     price:69,  orig:699,  badge:"bestseller",  emoji:"🌧️" },
  { id:1217060, name:"Gunfire Reborn",                    genre:"Shooter",  sub:"Roguelite",     price:69,  orig:699,  badge:"",            emoji:"🔫" },
  { id:236390,  name:"War Thunder",                       genre:"Shooter",  sub:"Military",      price:49,  orig:399,  badge:"",            emoji:"✈️" },

  /* ── HORROR ──────────────────────────────────────────── */
  { id:1196590, name:"Resident Evil Village",             genre:"Horror",   sub:"Survival",      price:149, orig:2499, badge:"hot",         emoji:"🧟" },
  { id:534380,  name:"Dying Light 2 Stay Human",          genre:"Horror",   sub:"Parkour",       price:129, orig:2499, badge:"",            emoji:"🌆" },
  { id:870780,  name:"Control Ultimate Edition",          genre:"Horror",   sub:"Supernatural",  price:79,  orig:1499, badge:"",            emoji:"🏢" },
  { id:2050650, name:"Resident Evil 4 Remake",            genre:"Horror",   sub:"Survival",      price:169, orig:3499, badge:"new",         emoji:"🌽" },
  { id:1089560, name:"Alan Wake 2",                       genre:"Horror",   sub:"Thriller",      price:169, orig:3499, badge:"new",         emoji:"🔦" },
  { id:238320,  name:"Outlast",                           genre:"Horror",   sub:"Survival",      price:49,  orig:399,  badge:"",            emoji:"📹" },
  { id:414700,  name:"Outlast 2",                         genre:"Horror",   sub:"Survival",      price:49,  orig:499,  badge:"",            emoji:"📹" },
  { id:282140,  name:"SOMA",                              genre:"Horror",   sub:"Sci-Fi",        price:49,  orig:499,  badge:"",            emoji:"🤖" },
  { id:860510,  name:"Little Nightmares II",              genre:"Horror",   sub:"Puzzle",        price:79,  orig:699,  badge:"",            emoji:"🏮" },
  { id:424840,  name:"Little Nightmares",                 genre:"Horror",   sub:"Puzzle",        price:49,  orig:399,  badge:"",            emoji:"🏮" },
  { id:304430,  name:"INSIDE",                            genre:"Horror",   sub:"Puzzle",        price:49,  orig:299,  badge:"",            emoji:"🔦" },
  { id:48000,   name:"LIMBO",                             genre:"Horror",   sub:"Puzzle",        price:39,  orig:249,  badge:"",            emoji:"🕷️" },
  { id:242760,  name:"The Forest",                        genre:"Horror",   sub:"Survival",      price:69,  orig:699,  badge:"",            emoji:"🌲" },
  { id:264710,  name:"Subnautica",                        genre:"Horror",   sub:"Survival",      price:79,  orig:799,  badge:"bestseller",  emoji:"🐠" },
  { id:848450,  name:"Subnautica: Below Zero",            genre:"Horror",   sub:"Survival",      price:79,  orig:799,  badge:"",            emoji:"🧊" },
  { id:214490,  name:"Alien: Isolation",                  genre:"Horror",   sub:"Sci-Fi",        price:79,  orig:699,  badge:"",            emoji:"👾" },
  { id:739630,  name:"Phasmophobia",                      genre:"Horror",   sub:"Co-op",         price:69,  orig:799,  badge:"bestseller",  emoji:"👻" },
  { id:381210,  name:"Dead by Daylight",                  genre:"Horror",   sub:"Multiplayer",   price:69,  orig:699,  badge:"",            emoji:"🔪" },
  { id:747660,  name:"FNAF: Security Breach",             genre:"Horror",   sub:"Stealth",       price:79,  orig:699,  badge:"",            emoji:"🐻" },
  { id:999220,  name:"Amnesia: Rebirth",                  genre:"Horror",   sub:"Survival",      price:49,  orig:499,  badge:"",            emoji:"🌑" },

  /* ── SPORTS ──────────────────────────────────────────── */
  { id:2195250, name:"EA Sports FC 24",                   genre:"Sports",   sub:"Football",      price:149, orig:3999, badge:"hot",         emoji:"⚽" },
  { id:1811260, name:"FIFA 23",                           genre:"Sports",   sub:"Football",      price:99,  orig:2499, badge:"",            emoji:"⚽" },
  { id:2108330, name:"F1 23",                             genre:"Sports",   sub:"Racing",        price:129, orig:2999, badge:"",            emoji:"🏎️" },
  { id:1551360, name:"Forza Horizon 5",                   genre:"Sports",   sub:"Racing",        price:129, orig:2999, badge:"bestseller",  emoji:"🏁" },
  { id:1222680, name:"Need for Speed Heat",               genre:"Sports",   sub:"Racing",        price:99,  orig:1999, badge:"",            emoji:"🚗" },
  { id:2338770, name:"NBA 2K24",                          genre:"Sports",   sub:"Basketball",    price:109, orig:2499, badge:"",            emoji:"🏀" },
  { id:1784870, name:"WWE 2K23",                          genre:"Sports",   sub:"Wrestling",     price:99,  orig:1999, badge:"",            emoji:"🤼" },
  { id:252950,  name:"Rocket League",                     genre:"Sports",   sub:"Soccer",        price:49,  orig:399,  badge:"bestseller",  emoji:"🚀" },
  { id:244210,  name:"Assetto Corsa",                     genre:"Sports",   sub:"Sim Racing",    price:69,  orig:799,  badge:"",            emoji:"🏎️" },
  { id:805550,  name:"Assetto Corsa Competizione",        genre:"Sports",   sub:"Sim Racing",    price:79,  orig:999,  badge:"",            emoji:"🏎️" },
  { id:228380,  name:"Wreckfest",                         genre:"Sports",   sub:"Racing",        price:79,  orig:999,  badge:"",            emoji:"💥" },
  { id:690790,  name:"DiRT Rally 2.0",                    genre:"Sports",   sub:"Rally",         price:79,  orig:999,  badge:"",            emoji:"🚗" },
  { id:1307870, name:"GRID Legends",                      genre:"Sports",   sub:"Racing",        price:69,  orig:1499, badge:"",            emoji:"🏁" },
  { id:1049840, name:"Riders Republic",                   genre:"Sports",   sub:"Extreme",       price:89,  orig:1499, badge:"",            emoji:"🚵" },
  { id:1685350, name:"PGA Tour 2K23",                     genre:"Sports",   sub:"Golf",          price:79,  orig:1499, badge:"",            emoji:"⛳" },
  { id:1880360, name:"Tony Hawk's Pro Skater 1+2",        genre:"Sports",   sub:"Skateboarding", price:89,  orig:1499, badge:"",            emoji:"🛹" },

  /* ── ADVENTURE ───────────────────────────────────────── */
  { id:1190460, name:"Death Stranding",                   genre:"Adventure",sub:"Sci-Fi",        price:129, orig:1999, badge:"",            emoji:"📦" },
  { id:1426210, name:"It Takes Two",                      genre:"Adventure",sub:"Co-op",         price:99,  orig:1499, badge:"bestseller",  emoji:"👫" },
  { id:1898300, name:"A Plague Tale: Requiem",            genre:"Adventure",sub:"Story",         price:139, orig:3499, badge:"new",         emoji:"🐀" },
  { id:1888930, name:"The Last of Us Part I",             genre:"Adventure",sub:"Survival",      price:199, orig:3999, badge:"hot",         emoji:"🍄" },
  { id:413150,  name:"Stardew Valley",                    genre:"Adventure",sub:"Farming",       price:49,  orig:499,  badge:"",            emoji:"🌾" },
  { id:892970,  name:"Valheim",                           genre:"Adventure",sub:"Survival",      price:79,  orig:849,  badge:"",            emoji:"🪓" },
  { id:1659420, name:"Uncharted: Legacy of Thieves",      genre:"Adventure",sub:"Story",         price:149, orig:2499, badge:"",            emoji:"🗺️" },
  { id:632470,  name:"Disco Elysium",                     genre:"Adventure",sub:"RPG",           price:79,  orig:999,  badge:"bestseller",  emoji:"🕵️" },
  { id:753640,  name:"Outer Wilds",                       genre:"Adventure",sub:"Exploration",   price:79,  orig:799,  badge:"bestseller",  emoji:"🌌" },
  { id:501300,  name:"What Remains of Edith Finch",       genre:"Adventure",sub:"Story",         price:49,  orig:399,  badge:"",            emoji:"🏠" },
  { id:383870,  name:"Firewatch",                         genre:"Adventure",sub:"Mystery",       price:49,  orig:399,  badge:"",            emoji:"🔥" },
  { id:972660,  name:"Spiritfarer",                       genre:"Adventure",sub:"Indie",         price:69,  orig:699,  badge:"",            emoji:"⛵" },
  { id:1057090, name:"Ori and the Will of the Wisps",     genre:"Adventure",sub:"Platformer",    price:69,  orig:699,  badge:"bestseller",  emoji:"✨" },
  { id:261570,  name:"Ori and the Blind Forest",          genre:"Adventure",sub:"Platformer",    price:49,  orig:499,  badge:"",            emoji:"✨" },
  { id:1325200, name:"Kena: Bridge of Spirits",           genre:"Adventure",sub:"Action",        price:89,  orig:1499, badge:"",            emoji:"🌿" },
  { id:553420,  name:"Tunic",                             genre:"Adventure",sub:"Puzzle",        price:79,  orig:799,  badge:"",            emoji:"🦊" },
  { id:638230,  name:"Journey",                           genre:"Adventure",sub:"Indie",         price:49,  orig:399,  badge:"",            emoji:"🏜️" },
  { id:105600,  name:"Terraria",                          genre:"Adventure",sub:"Sandbox",       price:49,  orig:399,  badge:"bestseller",  emoji:"🌍" },
  { id:1135690, name:"Unpacking",                         genre:"Adventure",sub:"Puzzle",        price:49,  orig:499,  badge:"",            emoji:"📦" },
  { id:275850,  name:"No Man's Sky",                      genre:"Adventure",sub:"Space",         price:99,  orig:1499, badge:"bestseller",  emoji:"🌌" },
  { id:361420,  name:"Astroneer",                         genre:"Adventure",sub:"Space",         price:69,  orig:799,  badge:"",            emoji:"🚀" },
  { id:648800,  name:"Raft",                              genre:"Adventure",sub:"Survival",      price:69,  orig:699,  badge:"",            emoji:"🪵" },
  { id:1055540, name:"A Short Hike",                      genre:"Adventure",sub:"Casual",        price:39,  orig:199,  badge:"",            emoji:"🏔️" },
  { id:1898300, name:"Season: A Letter to the Future",    genre:"Adventure",sub:"Story",         price:69,  orig:799,  badge:"",            emoji:"📷" },
  { id:962130,  name:"Grounded",                          genre:"Adventure",sub:"Survival",      price:79,  orig:999,  badge:"",            emoji:"🐜" },

  /* ── STRATEGY ────────────────────────────────────────── */
  { id:1466860, name:"Age of Empires IV",                 genre:"Strategy", sub:"RTS",           price:119, orig:1999, badge:"",            emoji:"🏰" },
  { id:289070,  name:"Civilization VI",                   genre:"Strategy", sub:"Turn-based",    price:89,  orig:1199, badge:"",            emoji:"🌍" },
  { id:2183900, name:"Warhammer 40K: Space Marine 2",     genre:"Strategy", sub:"Action",        price:179, orig:3499, badge:"new",         emoji:"⚙️" },
  { id:526870,  name:"Satisfactory",                      genre:"Strategy", sub:"Factory",       price:89,  orig:999,  badge:"",            emoji:"🏭" },
  { id:246620,  name:"Plague Inc: Evolved",               genre:"Strategy", sub:"Simulation",    price:59,  orig:599,  badge:"",            emoji:"🦠" },
  { id:255710,  name:"Cities: Skylines",                  genre:"Strategy", sub:"City Builder",  price:79,  orig:999,  badge:"bestseller",  emoji:"🏙️" },
  { id:949230,  name:"Cities: Skylines 2",                genre:"Strategy", sub:"City Builder",  price:149, orig:2499, badge:"new",         emoji:"🏙️" },
  { id:323190,  name:"Frostpunk",                         genre:"Strategy", sub:"Survival",      price:69,  orig:799,  badge:"",            emoji:"❄️" },
  { id:1904990, name:"Frostpunk 2",                       genre:"Strategy", sub:"Survival",      price:129, orig:2499, badge:"new",         emoji:"❄️" },
  { id:1158310, name:"Crusader Kings III",                genre:"Strategy", sub:"Grand",         price:99,  orig:1499, badge:"bestseller",  emoji:"👑" },
  { id:281990,  name:"Stellaris",                         genre:"Strategy", sub:"Space",         price:89,  orig:999,  badge:"",            emoji:"🌌" },
  { id:394360,  name:"Hearts of Iron IV",                 genre:"Strategy", sub:"WW2",           price:89,  orig:999,  badge:"",            emoji:"⚔️" },
  { id:1142710, name:"Total War: WARHAMMER III",          genre:"Strategy", sub:"RTS",           price:99,  orig:1999, badge:"",            emoji:"⚔️" },
  { id:779340,  name:"Total War: Three Kingdoms",         genre:"Strategy", sub:"RTS",           price:79,  orig:1499, badge:"",            emoji:"⚔️" },
  { id:268500,  name:"XCOM 2",                            genre:"Strategy", sub:"Turn-based",    price:79,  orig:999,  badge:"",            emoji:"👾" },
  { id:646570,  name:"Slay the Spire",                    genre:"Strategy", sub:"Roguelike",     price:69,  orig:799,  badge:"bestseller",  emoji:"🃏" },
  { id:1092790, name:"Inscryption",                       genre:"Strategy", sub:"Roguelike",     price:69,  orig:699,  badge:"",            emoji:"🃏" },
  { id:457140,  name:"Oxygen Not Included",               genre:"Strategy", sub:"Simulation",    price:69,  orig:799,  badge:"",            emoji:"🫧" },
  { id:294100,  name:"RimWorld",                          genre:"Strategy", sub:"Simulation",    price:89,  orig:999,  badge:"bestseller",  emoji:"🚀" },
  { id:703080,  name:"Planet Zoo",                        genre:"Strategy", sub:"Simulation",    price:89,  orig:1499, badge:"",            emoji:"🦁" },
  { id:493340,  name:"Planet Coaster",                    genre:"Strategy", sub:"Simulation",    price:79,  orig:999,  badge:"",            emoji:"🎢" },
  { id:529340,  name:"Victoria 3",                        genre:"Strategy", sub:"Grand",         price:99,  orig:1999, badge:"",            emoji:"🏛️" },
  { id:1794680, name:"Vampire Survivors",                 genre:"Strategy", sub:"Roguelite",     price:49,  orig:249,  badge:"bestseller",  emoji:"🧛" },
  { id:975370,  name:"Dwarf Fortress (Premium)",          genre:"Strategy", sub:"Simulation",    price:69,  orig:699,  badge:"",            emoji:"⛏️" },
  { id:346110,  name:"ARK: Survival Evolved",             genre:"Strategy", sub:"Survival",      price:79,  orig:999,  badge:"",            emoji:"🦕" },

  /* ── INDIE ───────────────────────────────────────────── */
  { id:391540,  name:"Undertale",                         genre:"Indie",    sub:"RPG",           price:49,  orig:299,  badge:"",            emoji:"❤️" },
  { id:250900,  name:"The Binding of Isaac: Rebirth",     genre:"Indie",    sub:"Roguelite",     price:49,  orig:399,  badge:"bestseller",  emoji:"😢" },
  { id:588650,  name:"Dead Cells",                        genre:"Indie",    sub:"Roguelite",     price:69,  orig:699,  badge:"bestseller",  emoji:"⚔️" },
  { id:1253920, name:"Rogue Legacy 2",                    genre:"Indie",    sub:"Roguelite",     price:69,  orig:699,  badge:"",            emoji:"🏰" },
  { id:311690,  name:"Enter the Gungeon",                 genre:"Indie",    sub:"Roguelite",     price:69,  orig:399,  badge:"",            emoji:"🔫" },
  { id:1282730, name:"Loop Hero",                         genre:"Indie",    sub:"Roguelite",     price:49,  orig:399,  badge:"",            emoji:"🔄" },
  { id:1102190, name:"Monster Train",                     genre:"Indie",    sub:"Deckbuilder",   price:69,  orig:699,  badge:"",            emoji:"🚂" },
  { id:1868140, name:"Dave the Diver",                    genre:"Indie",    sub:"Simulation",    price:89,  orig:799,  badge:"bestseller",  emoji:"🤿" },
  { id:2231450, name:"Pizza Tower",                       genre:"Indie",    sub:"Platformer",    price:49,  orig:399,  badge:"new",         emoji:"🍕" },
  { id:736260,  name:"Baba Is You",                       genre:"Indie",    sub:"Puzzle",        price:49,  orig:399,  badge:"",            emoji:"🐑" },
  { id:683520,  name:"GRIS",                              genre:"Indie",    sub:"Platformer",    price:49,  orig:399,  badge:"",            emoji:"🎨" },
  { id:881100,  name:"Noita",                             genre:"Indie",    sub:"Roguelite",     price:69,  orig:799,  badge:"",            emoji:"🧪" },
  { id:945360,  name:"Among Us",                          genre:"Indie",    sub:"Social",        price:49,  orig:199,  badge:"",            emoji:"👾" },
  { id:1097150, name:"Fall Guys",                         genre:"Indie",    sub:"Battle Royale", price:49,  orig:399,  badge:"",            emoji:"🎮" },
  { id:760620,  name:"FTL: Faster Than Light",            genre:"Indie",    sub:"Roguelite",     price:49,  orig:299,  badge:"",            emoji:"🚀" },
  { id:1794680, name:"Vampire Survivors",                 genre:"Indie",    sub:"Roguelite",     price:49,  orig:249,  badge:"",            emoji:"🧛" },

  /* ── FIGHTING ────────────────────────────────────────── */
  { id:976310,  name:"Mortal Kombat 11",                  genre:"Fighting", sub:"Fighting",      price:89,  orig:1499, badge:"",            emoji:"🥊" },
  { id:1971870, name:"Mortal Kombat 1",                   genre:"Fighting", sub:"Fighting",      price:149, orig:2999, badge:"new",         emoji:"🥊" },
  { id:1877960, name:"Street Fighter 6",                  genre:"Fighting", sub:"Fighting",      price:149, orig:2999, badge:"hot",         emoji:"🥊" },
  { id:1384160, name:"Guilty Gear -Strive-",              genre:"Fighting", sub:"Fighting",      price:99,  orig:1499, badge:"",            emoji:"🎸" },
  { id:678950,  name:"Dragon Ball FighterZ",              genre:"Fighting", sub:"Anime",         price:79,  orig:1499, badge:"",            emoji:"🐉" },
  { id:389730,  name:"Tekken 7",                          genre:"Fighting", sub:"Fighting",      price:89,  orig:1499, badge:"",            emoji:"🥊" },
  { id:1778820, name:"Tekken 8",                          genre:"Fighting", sub:"Fighting",      price:149, orig:2999, badge:"new",         emoji:"🥊" },
  { id:544750,  name:"SoulCalibur VI",                    genre:"Fighting", sub:"Weapons",       price:79,  orig:1499, badge:"",            emoji:"⚔️" },
  { id:304390,  name:"For Honor",                         genre:"Fighting", sub:"Medieval",      price:69,  orig:999,  badge:"",            emoji:"⚔️" },
  { id:627690,  name:"Injustice 2",                       genre:"Fighting", sub:"Superhero",     price:69,  orig:999,  badge:"",            emoji:"🦸" },

];

// Filter out EA Sports / FIFA / EA FC games completely
if (typeof GAMES_DATA !== 'undefined') {
  GAMES_DATA = GAMES_DATA.filter(g => !/ea\s*sports|fifa|fc\s*2[45]|madden/i.test(g.name));
}

